### ISSUE TITLE
Add _info: comment field in BasicTests

### ISSUE THREAD

**Issue by pirapira** [ethereum/tests#340] opened 2017-09-25 09:42 UTC
Currently, some files in BasicTests do not have any comments.  This issue keeps track of adding comments.

Perheps
```
"_info" : {
  "comment" : "Some description of the test, used forkblock numbers and so on."
}
```
is a good format.

**Comment by winsvega** [comment] 2017-09-26 14:46
duplicate of https://github.com/ethereum/tests/issues/332

**Closed as completed** 2021-03-25 13:13 UTC
Labels: duplicate, can-be-closed-imao
