### ISSUE TITLE
Update state test docs to include need to touch coinbase

### ISSUE THREAD

**Issue by germsvel** [ethereum/tests#513] opened 2018-10-01 19:14 UTC
[Mana](https://github.com/poanetwork/mana) had a few state tests that took us a long time to figure out how to pass. After doing some research, we discovered [this conversation in gitter](https://gitter.im/ethereum/tests?at=5b85004aff445156164b685f) that led us to understand that we needed to simulate adding a miner reward and cleaning up empty accounts after EIP-161. The PR introducing those changes to `mana` is [here](https://github.com/poanetwork/mana/pull/463).

The behavior is very unexpected based on the [current state tests docs](https://ethereum-tests.readthedocs.io/en/latest/test_types/state_tests.html) since there is no mention of that at all. 

Could we update the docs to include a mention of that or should the tests be changed so that they do not depend on simulating a miner reward?

**Comment by winsvega** [comment] 2018-11-19 18:40
Sorry about that. This change is a part of prepearing existing test cases to be able to run as a blockchain tests.

I don't see this change added to the docs, although the issue is referenced in move docs PR.

**Comment by winsvega** [comment] 2020-06-19 19:39
fixed by https://github.com/ethereum/tests/pull/698

**Comment by winsvega** [comment] 2020-06-29 17:31
https://github.com/ethereum/tests/commit/fd7ba2d23911855a9a988755877b2b39f74552d5#diff-60e4f9cfbacdcc41ce1a5c1829992a44L11

**Closed as completed by winsvega** 2020-06-29 17:31 UTC
Labels: documentation
